package com.wuyue.dllo.mirror.cache;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.wuyue.dllo.mirror.cache.InForEntity;

import com.wuyue.dllo.mirror.cache.InForEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig inForEntityDaoConfig;

    private final InForEntityDao inForEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        inForEntityDaoConfig = daoConfigMap.get(InForEntityDao.class).clone();
        inForEntityDaoConfig.initIdentityScope(type);

        inForEntityDao = new InForEntityDao(inForEntityDaoConfig, this);

        registerDao(InForEntity.class, inForEntityDao);
    }
    
    public void clear() {
        inForEntityDaoConfig.getIdentityScope().clear();
    }

    public InForEntityDao getInForEntityDao() {
        return inForEntityDao;
    }

}
