package com.wuyue.dllo.mirror.cache;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "IN_FOR_ENTITY".
 */
public class InForEntity {

    private Long id;
    private String name;

    public InForEntity() {
    }

    public InForEntity(Long id) {
        this.id = id;
    }

    public InForEntity(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
