package com.wuyue.dllo.mirror.picturedownloader;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.wuyue.dllo.mirror.picturedownloader.PLEntity;

import com.wuyue.dllo.mirror.picturedownloader.PLEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pLEntityDaoConfig;

    private final PLEntityDao pLEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pLEntityDaoConfig = daoConfigMap.get(PLEntityDao.class).clone();
        pLEntityDaoConfig.initIdentityScope(type);

        pLEntityDao = new PLEntityDao(pLEntityDaoConfig, this);

        registerDao(PLEntity.class, pLEntityDao);
    }
    
    public void clear() {
        pLEntityDaoConfig.getIdentityScope().clear();
    }

    public PLEntityDao getPLEntityDao() {
        return pLEntityDao;
    }
}
