package com.wuyue.dllo.mirror.picturedownloader;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PLENTITY".
 */
public class PLEntity {

    private Long id;
    private String uri;
    private String name;
    private String area;
    private String brand;
    private String price;

    public PLEntity() {
    }

    public PLEntity(Long id) {
        this.id = id;
    }

    public PLEntity(Long id, String uri, String name, String area, String brand, String price) {
        this.id = id;
        this.uri = uri;
        this.name = name;
        this.area = area;
        this.brand = brand;
        this.price = price;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

}
